name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
#     - run: npm test
    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 3.111.73.149
        username: ec2-user
        password: toor
        port: 22
        script: |
          whoami
          ls -al
          cd Document/
          ls -al
          mkdir hahBit
