name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Print Public IP
      shell: bash
      run: |
        curl api.ipify.org
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
#     - run: npm test
    - name: ZIpping Files!
      shell: bash
      run: |
        sudo apt update -y && sudo apt install -y python3-pip
        pwd
        ls -al
        zip -r build.zip public/*
        python3 --version
        pip3 --version
        pip3 install PyDrive
        python3 uploader.py
        
        
        
    
